### ISSUE TITLE
no requirments.txt for the python utils

### ISSUE THREAD

**Issue by paulhayes** [lowtechmag/solar_v2#4]
The python utils require third party modules, which aren't listed
```
hitherdither @ git+https://www.github.com/hbldh/hitherdither
bs4
Pillow
```
A requirements.txt should probably be added to the utils dir.

**Comment by rscmbbng** [comment]
Hi Paul,

The requirements are listed in the [README](https://github.com/lowtechmag/solar_v2?tab=readme-ov-file#dithering-tool).
If you want to find out the minimum required versions of the deps for the python scripts and submit a PR we can merge it!
